name: ci

on:
    pull_request:
        branches: [main]

jobs:
    tests:
        name: Tests
        runs-on: ubuntu-latest

        steps:
        -   name: Check out code
            uses: actions/checkout@v4

        -   name: Set up Go
            uses: actions/setup-go@v5
            with:
                go-version: "1.25.1"

        -   name: run tests with coverage
            run: go test ./... -cover

        -   name: run go vet
            run: go vet ./...

    style:
        name: Style
        runs-on: ubuntu-latest

        steps:
        -   name: Check out code
            uses: actions/checkout@v4

        -   name: Set up Go
            uses: actions/setup-go@v5
            with:
                go-version: "1.25.1"

        -   name: run go fmt
            run: test -z "$(go fmt -l ./...)"

        -   name: Install staticcheck
            run: go install honnef.co/go/tools/cmd/staticcheck@latest

        -   name: run staticcheck
            run: staticcheck ./...

    security:
        name: Security
        runs-on: ubuntu-latest

        steps:
        -   name: Check out code
            uses: actions/checkout@v4

        -   name: Set up Go
            uses: actions/setup-go@v5
            with:
                go-version: "1.25.1"

        -   name: Install govulncheck
            run: go install golang.org/x/vuln/cmd/govulncheck@latest
            
        -   name: run govulncheck
            run: govulncheck ./...

        -   name: Install gosec
            run: go install github.com/securego/gosec/v2/cmd/gosec@latest

        -   name: run gosec
            run: gosec ./...